/** Generated by scripts/render-og-urna-batch.mjs */
export const OG_URNA_KEYS = new Set<string>([
  "al-governor-jhc",
  "al-governor-renanfilho",
  "ba-governor-acmneto",
  "ba-governor-jeronimo",
  "mt-governor-otavianopivetta",
  "mt-governor-wellingtonfagundes",
  "pa-governor-drdaniel",
  "pa-governor-hana",
  "rn-governor-cadudelula",
  "rn-governor-rodrigovieira",
  "ro-governor-furia",
  "ro-governor-marcosrogerio",
]);
